### ISSUE TITLE
Strings with $ in the grammar don't escape $ in PHP

### ISSUE THREAD

**Issue by mkasberg** [Nordth/php-pegjs#4]
For example, 

$callback from the grammar at https://github.com/auth0/node-odata-parser/blob/master/src/odata.pegjs on line 182.

results in 

```
$this->peg_c117 = "$callback=";
$this->peg_c118 = array( "type" => "literal", "value" => "$callback=", "description" => "\"$callback=\"" );
```

but should result in

```
$this->peg_c117 = "\$callback=";
$this->peg_c118 = array( "type" => "literal", "value" => "\$callback=", "description" => "\"\$callback=\"" );
```

Without the escaped character, PHP tries to interpret $callback as a variable since it is in a double-quote string.

**Comment by Nordth** [comment]
Possible fixed by 186f0bd
